alias ds='git diff --staged'
alias dsc='git diff --staged --color-words'
alias aa='git add . && git status'
alias lp='git log --patch --stat'
alias lo='git log --graph --oneline --decorate'
alias bb='git branch'
alias co='git checkout'
alias gr='git log --all --pretty=format:"%Cred%h %Cblue%ar%Creset %Cgreen%an%Creset %s %Cred%d" --graph'
alias fxp='git commit --fixup'
alias sv='git add . && git commit -m "`git rev-parse --abbrev-ref HEAD` save" && git push'
alias usv='git reset HEAD~1'
alias gdob='for branch in $(git branch --merged | grep -v master); do git branch -d $branch; done'
alias um='git checkout master && git fetch --prune && gdob ; git merge origin/master'
alias ud='git checkout develop && git fetch --prune && gdob ; git merge origin/develop'
alias rbz='git rebase -i --autosquash'
alias rom='um && git checkout - && rbz master'
alias rod='git checkout develop && git pull && git checkout - && rbz develop'
alias tfx='git commit --message=typofix && git pull --rebase && git push'
alias zbs='git rebase --continue'
alias nah='git rebase --skip'
alias nvm='git rebase --abort'

mergeof(){ git log $1..master --merges --oneline | tail -n 1 | cut -d ' ' -f 1 | xargs git show }
